// packages/ui/src/utils/icons.ts
//
// Punto unico di importazione delle icone Lucide del progetto.
//
// Tutti i componenti — sia dentro @edg/ui sia nelle app che lo consumano —
// importano le icone da qui invece che direttamente da 'lucide-react':
//   - componenti interni a @edg/ui  → import relativo (es. '../../utils/icons')
//   - consumer esterni (apps/*, packages/auth) → import { Edit } from '@edg/ui'
// Un solo catalogo, aggiornato in un solo punto. Alimenta anche la pagina
// DESIGN > Icone (packages/ui/src/explorer/IconsPreview.tsx).
//
// Per aggiungere una nuova icona al progetto: importarla ed esportarla qui
// (il nome deve coincidere con l'export di lucide-react), poi aggiungerla
// anche a ICONS per farla comparire nel catalogo.

import {
  AlertCircle,
  AlertTriangle,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Bell,
  Building2,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Copy,
  Database,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  Home,
  House,
  LayoutGrid,
  Lock,
  LogOut,
  Mail,
  Menu,
  MoreVertical,
  Palette,
  Puzzle,
  RefreshCw,
  Search,
  Settings,
  Shield,
  Timer,
  Trash2,
  Unlock,
  Upload,
  User,
  X,
  type LucideIcon,
} from 'lucide-react';

export {
  AlertCircle,
  AlertTriangle,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Bell,
  Building2,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Copy,
  Database,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  Home,
  House,
  LayoutGrid,
  Lock,
  LogOut,
  Mail,
  Menu,
  MoreVertical,
  Palette,
  Puzzle,
  RefreshCw,
  Search,
  Settings,
  Shield,
  Timer,
  Trash2,
  Unlock,
  Upload,
  User,
  X,
};

export type { LucideIcon };

/** Catalogo nome → componente: alimenta la pagina DESIGN > Icone. */
export const ICONS: Record<string, LucideIcon> = {
  AlertCircle,
  AlertTriangle,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Bell,
  Building2,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Copy,
  Database,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  Home,
  House,
  LayoutGrid,
  Lock,
  LogOut,
  Mail,
  Menu,
  MoreVertical,
  Palette,
  Puzzle,
  RefreshCw,
  Search,
  Settings,
  Shield,
  Timer,
  Trash2,
  Unlock,
  Upload,
  User,
  X,
};
